---
- name: Check if /etc/default/ufw exists
  stat:
    path: /etc/default/ufw
  register: ufw_default_exists

- name: Change ufw default forward policy from drop to accept
  lineinfile:
    dest: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY=\"ACCEPT\"'
  when: ufw_default_exists.stat.exists
  tags:
  - docker
  - ufw

- name: Configure | Allow External Connections
  lineinfile:
    dest: /etc/init/docker.conf
    regexp: 'DOCKER_OPTS='
    line: 'DOCKER_OPTS="-H unix:///var/run/docker.sock -H 0.0.0.0:2375"'
  when: docker_accepts_external_connections
  notify: service | docker | reloaded
  tags:
  - docker
